.gitignore
.travis.yml
backend/Dockerfile
backend/src/main/resources/application-docker.properties
docker-compose.yml
frontend/Dockerfile

Feature/docker support (Fix #90)

---

backend/src/main/java/io/suricate/monitoring/service/DashboardScheduleService.java
backend/src/main/java/io/suricate/monitoring/service/GitService.java
backend/src/main/java/io/suricate/monitoring/service/api/ProjectWidgetService.java
backend/src/main/java/io/suricate/monitoring/service/api/WidgetService.java
backend/src/main/java/io/suricate/monitoring/service/nashorn/NashornWidgetExecutor.java
backend/src/main/java/io/suricate/monitoring/service/nashorn/task/NashornResultAsyncTask.java
backend/src/main/java/io/suricate/monitoring/service/nashorn/task/NashornWidgetExecuteAsyncTask.java
backend/src/main/java/io/suricate/monitoring/utils/MonitorProxySelector.java
backend/src/main/java/io/suricate/monitoring/utils/OkHttpClientUtils.java
backend/src/test/java/io/suricate/monitoring/service/api/LibraryServiceTest.java
backend/src/test/java/io/suricate/monitoring/service/api/WidgetServiceTest.java
backend/src/test/java/io/suricate/monitoring/service/nashorn/JavaClassFilterTest.java
backend/src/test/java/io/suricate/monitoring/service/nashorn/NashornWidgetExecutorTest.java
backend/src/test/java/io/suricate/monitoring/service/nashorn/task/NashornWidgetExecuteAsyncTaskTest.java

- Retrieve widgets variable params from database instead of Widget JS file
- Fix Bug when launching Nashorn request with retrofit if proxy is null
- Delete retrofit show request properties
- Add exception stack trace when narshorn request fail

Issue #147 - Feature/prepare nashorn request

---

backend/src/main/java/io/suricate/monitoring/repository/ProjectRepository.java
backend/src/main/java/io/suricate/monitoring/repository/ProjectWidgetRepository.java
backend/src/main/java/io/suricate/monitoring/service/api/ProjectService.java
backend/src/main/java/io/suricate/monitoring/service/api/ProjectWidgetService.java
backend/src/main/java/io/suricate/monitoring/service/nashorn/NashornService.java
backend/src/main/java/io/suricate/monitoring/service/scheduler/NashornWidgetScheduler.java
backend/src/main/java/io/suricate/monitoring/service/webSocket/DashboardWebSocketService.java

Instantiate a project only when it's need not when the serveur is starting up

Issue #73 - Instantiate a project only when it's need 

---

backend/src/main/java/io/suricate/monitoring/controllers/api/UserController.java
backend/src/main/java/io/suricate/monitoring/repository/UserRepository.java
backend/src/main/java/io/suricate/monitoring/service/api/UserService.java
frontend/src/app/app.component.html
frontend/src/app/modules/core/sidenav/sidenav.component.css
frontend/src/app/modules/core/sidenav/sidenav.component.html
frontend/src/app/modules/user/components/delete-user-dialog/delete-user-dialog.component.html
frontend/src/app/modules/user/components/delete-user-dialog/delete-user-dialog.component.spec.ts
frontend/src/app/modules/user/components/delete-user-dialog/delete-user-dialog.component.ts
frontend/src/app/modules/user/user-edit/user-edit.component.css
frontend/src/app/modules/user/user-edit/user-edit.component.html
frontend/src/app/modules/user/user-edit/user-edit.component.spec.ts
frontend/src/app/modules/user/user-edit/user-edit.component.ts
frontend/src/app/modules/user/user-list/user-list.component.css
frontend/src/app/modules/user/user-list/user-list.component.html
frontend/src/app/modules/user/user-list/user-list.component.ts
frontend/src/app/modules/user/user.module.ts
frontend/src/app/modules/user/user.service.ts
frontend/src/app/shared/components/toast/toast.component.css
frontend/src/app/shared/components/toast/toast.component.html
frontend/src/app/shared/components/toast/toast.component.spec.ts
frontend/src/app/shared/components/toast/toast.component.ts
frontend/src/app/shared/components/toast/toast.service.spec.ts
frontend/src/app/shared/components/toast/toast.service.ts
frontend/src/app/shared/model/dto/user/User.ts
frontend/src/app/shared/model/toastNotification/ToastMessage.ts
frontend/src/app/shared/model/toastNotification/ToastType.ts
frontend/src/app/shared/shared.module.ts
frontend/src/styles.css
frontend/src/tsconfig.app.json

- Able to delete / Edit a User
- Display REST message by ToasterNotification

Issue #76 - Feature/user management

---

backend/src/main/java/io/suricate/monitoring/controllers/api/ProjectController.java
backend/src/main/java/io/suricate/monitoring/model/mapper/project/ProjectWidgetMapper.java
backend/src/main/java/io/suricate/monitoring/service/api/ProjectService.java
frontend/src/app/modules/core/sidenav/sidenav.component.html
frontend/src/app/modules/core/sidenav/sidenav.component.ts
frontend/src/app/modules/dashboard/components/delete-dashboard-dialog/delete-dashboard-dialog.component.html
frontend/src/app/modules/dashboard/components/delete-dashboard-dialog/delete-dashboard-dialog.component.spec.ts
frontend/src/app/modules/dashboard/components/delete-dashboard-dialog/delete-dashboard-dialog.component.ts
frontend/src/app/modules/dashboard/dashboard-edit/dashboard-edit.component.css
frontend/src/app/modules/dashboard/dashboard-edit/dashboard-edit.component.html
frontend/src/app/modules/dashboard/dashboard-edit/dashboard-edit.component.spec.ts
frontend/src/app/modules/dashboard/dashboard-edit/dashboard-edit.component.ts
frontend/src/app/modules/dashboard/dashboard-list/dashboard-list.component.css
frontend/src/app/modules/dashboard/dashboard-list/dashboard-list.component.html
frontend/src/app/modules/dashboard/dashboard-list/dashboard-list.component.spec.ts
frontend/src/app/modules/dashboard/dashboard-list/dashboard-list.component.ts
frontend/src/app/modules/dashboard/dashboard.module.ts
frontend/src/app/modules/dashboard/dashboard.service.ts
frontend/src/app/shared/components/pages-header/components/add-dashboard-dialog/add-dashboard-dialog.component.html
frontend/src/app/shared/components/pages-header/components/add-dashboard-dialog/add-dashboard-dialog.component.ts
frontend/src/app/shared/components/toast/toast.component.css
frontend/src/app/shared/components/toast/toast.component.html
frontend/src/app/shared/services/abstract-http.service.ts

Edit dashboard from admin part

Issue #81 - Feature/dashboard management

---

backend/Dockerfile

Update Dockerfile for travis ci

---

frontend/src/app/modules/authentication/authentication.service.ts
frontend/src/app/modules/authentication/register/register.component.ts
frontend/src/app/modules/dashboard/dashboard.service.ts
frontend/src/app/modules/widget/widget-list/widget-list.component.html
frontend/src/app/modules/widget/widget-list/widget-list.component.ts
frontend/src/app/shared/components/toast/toast.component.css

- Fix bugs
- Display messages from request
- connect user when he's registered

Issue #204 - Feature/display notification

---

backend/src/main/java/io/suricate/monitoring/controllers/api/ProjectController.java
backend/src/main/java/io/suricate/monitoring/repository/ProjectWidgetRepository.java
backend/src/main/java/io/suricate/monitoring/service/api/ProjectWidgetService.java
frontend/src/app/modules/dashboard/components/delete-project-widget-dialog/delete-project-widget-dialog.component.html
frontend/src/app/modules/dashboard/components/delete-project-widget-dialog/delete-project-widget-dialog.component.spec.ts
frontend/src/app/modules/dashboard/components/delete-project-widget-dialog/delete-project-widget-dialog.component.ts
frontend/src/app/modules/dashboard/components/edit-project-widget-dialog/edit-project-widget-dialog.component.css
frontend/src/app/modules/dashboard/components/edit-project-widget-dialog/edit-project-widget-dialog.component.html
frontend/src/app/modules/dashboard/components/edit-project-widget-dialog/edit-project-widget-dialog.component.spec.ts
frontend/src/app/modules/dashboard/components/edit-project-widget-dialog/edit-project-widget-dialog.component.ts
frontend/src/app/modules/dashboard/dashboard-detail/dashboard-detail.component.html
frontend/src/app/modules/dashboard/dashboard-detail/dashboard-detail.component.ts
frontend/src/app/modules/dashboard/dashboard-list/dashboard-list.component.ts
frontend/src/app/modules/dashboard/dashboard.module.ts
frontend/src/app/modules/dashboard/dashboard.service.ts
frontend/src/app/shared/components/pages-header/components/add-dashboard-dialog/add-dashboard-dialog.component.ts
frontend/src/app/shared/components/toast/toast.service.ts
frontend/src/app/shared/model/websocket/WSUpdateEvent.ts
frontend/src/app/shared/pipes/safe-html.pipe.spec.ts
frontend/src/app/shared/pipes/safe-html.pipe.ts
frontend/src/app/shared/pipes/safe-url.pipe.spec.ts
frontend/src/app/shared/pipes/safe-url.pipe.ts
frontend/src/app/shared/shared.module.ts

Issue #85 - Feature/dashboard widget actions

---

.github/PULL_REQUEST_TEMPLATE.md

Add licence check for new file

---

frontend/src/app/modules/dashboard/components/dashboard-screen/dashboard-screen.component.css
frontend/src/app/modules/dashboard/components/dashboard-screen/dashboard-screen.component.html
frontend/src/app/modules/dashboard/components/dashboard-screen/dashboard-screen.component.ts
frontend/src/app/modules/dashboard/dashboard.service.ts
frontend/src/app/shared/services/websocket.service.ts

Display errors with remote server

Issue #84 - Feature/display dashboard widget errors

---

backend/src/main/java/io/suricate/monitoring/controllers/api/ScreenController.java
backend/src/main/java/io/suricate/monitoring/service/webSocket/DashboardWebSocketService.java
frontend/src/app/modules/dashboard/components/dashboard-screen/dashboard-screen.component.css
frontend/src/app/modules/dashboard/components/dashboard-screen/dashboard-screen.component.html
frontend/src/app/modules/dashboard/components/dashboard-screen/dashboard-screen.component.ts
frontend/src/app/modules/dashboard/screen.service.ts
frontend/src/app/shared/components/pages-header/components/tv-management-dialog/tv-management-dialog.component.css
frontend/src/app/shared/components/pages-header/components/tv-management-dialog/tv-management-dialog.component.html
frontend/src/app/shared/components/pages-header/components/tv-management-dialog/tv-management-dialog.component.ts

Issue #236 - Feature/display screen code on demand

---

frontend/src/app/app.component.html
frontend/src/app/modules/authentication/login/login.component.css
frontend/src/app/modules/authentication/register/register.component.css
frontend/src/app/modules/core/sidenav/sidenav.component.css
frontend/src/app/shared/components/pages-footer/pages-footer.component.css
frontend/src/app/shared/components/pages-footer/pages-footer.component.html
frontend/src/app/shared/shared.module.ts
frontend/src/styles.css

Finalize footer

---

docker-compose-dev.yml

Docker compose 4 dev env

---

frontend/src/app/shared/components/pages-header/components/dashboard-actions/dashboard-actions.component.html
frontend/src/app/shared/components/pages-header/components/dashboard-actions/dashboard-actions.component.ts

Issue #251 - Display TV View when click on the button

---

README.md

Switch CI to semaphoreci

---

frontend/src/app/modules/core/sidenav/sidenav.component.css
frontend/src/app/modules/core/sidenav/sidenav.component.html
frontend/src/app/modules/dashboard/dashboard-tv/dashboard-tv.component.ts
frontend/src/app/shared/services/settings.service.ts
frontend/src/assets/i18n/en.json
frontend/src/assets/i18n/fr.json
frontend/src/assets/styles/themes/shared/custom-theming-rules.scss

Issue #294 - Feature/home nav link

---

backend/src/main/java/io/suricate/monitoring/controllers/api/WidgetController.java
backend/src/main/java/io/suricate/monitoring/model/enums/ApiActionEnum.java
backend/src/main/java/io/suricate/monitoring/service/GitService.java
frontend/src/app/modules/dashboard/dashboard-tv/dashboard-tv.component.ts
frontend/src/app/modules/widget/widget-list/widget-list.component.ts
frontend/src/app/modules/widget/widget.service.ts
frontend/src/app/shared/components/pages-header/components/widget-list-actions/widget-list-actions.component.css
frontend/src/app/shared/components/pages-header/components/widget-list-actions/widget-list-actions.component.html
frontend/src/app/shared/components/pages-header/components/widget-list-actions/widget-list-actions.component.spec.ts
frontend/src/app/shared/components/pages-header/components/widget-list-actions/widget-list-actions.component.ts
frontend/src/app/shared/components/pages-header/pages-header.component.html
frontend/src/app/shared/model/dto/enums/ApiActionEnum.ts
frontend/src/app/shared/shared.module.ts

Reload widgets list form Git repository

#297 - Reload widgets on demand from Admin part

---

backend/src/main/java/io/suricate/monitoring/controllers/api/WidgetController.java
backend/src/main/java/io/suricate/monitoring/model/enums/ApiActionEnum.java

Issue #297 - Replace complex enum by a simple enum

---

frontend/src/app/modules/dashboard/dashboard.service.ts

Wrong element test in if instruction

Fix dashboard initialization

---

frontend/src/app/layout/header/components/repository-actions/repository-actions.component.css
frontend/src/app/layout/header/components/repository-actions/repository-actions.component.html
frontend/src/app/layout/header/components/repository-actions/repository-actions.component.spec.ts
frontend/src/app/layout/header/components/repository-actions/repository-actions.component.ts
frontend/src/app/layout/header/components/widget-list-actions/widget-list-actions.component.html
frontend/src/app/layout/header/components/widget-list-actions/widget-list-actions.component.ts
frontend/src/app/layout/header/pages/pages-header.component.html
frontend/src/app/layout/layout.module.ts
frontend/src/app/layout/sidenav/pages/sidenav.component.html
frontend/src/app/modules/dashboard/pages/admin/dashboard-list/dashboard-list.component.html
frontend/src/app/modules/widget/pages/admin/configuration/configuration-edit/widget-configuration-edit.component.html
frontend/src/app/modules/widget/pages/admin/configuration/configuration-list/widget-configuration-list.component.html
frontend/src/app/modules/widget/pages/admin/configuration/widget-configuration.route.ts
frontend/src/app/modules/widget/pages/admin/repository/repository-add-edit/repository-add-edit.component.ts
frontend/src/app/modules/widget/pages/admin/repository/repository.route.ts
frontend/src/app/modules/widget/widget.route.ts

#322 - refactor routes

---

frontend/src/app/layout/sidenav/pages/sidenav.component.html
frontend/src/app/modules/dashboard/dashboard.route.ts

- Only Admin can show the list of every dashboards
- Fix "Menu active" errors (if we display a dashboard the "all" entry is active too)

Switch URL for dashboards "all" menu entry

---

frontend/package.json
frontend/src/app/modules/widget/pages/admin/repository/repository-add-edit/repository-add-edit.component.ts

Go back to repository list when adding/edit

#327 - Go back to repository list when adding/edit

---

frontend/src/app/modules/widget/pages/admin/configuration/configuration-edit/widget-configuration-edit.component.ts

Redirect to widget configuration list page, after editing an existing conf

Issue #329 - redirect widget conf list when edit

---

frontend/src/app/modules/security/user/pages/user-edit/user-edit.component.ts

Go back to user list when editing successfully

#331 - Go back to user list when editing successfully

---

src/main/java/io/suricate/monitoring/BackendApplication.java
src/main/java/io/suricate/monitoring/controllers/api/RepositoryController.java
src/main/java/io/suricate/monitoring/controllers/api/WidgetController.java
src/main/java/io/suricate/monitoring/service/GitService.java

Reload repository when add or edit

Issue #333 - (Re)Load repository when add or edit

---

package.json
pom.xml

Fix CI to build a all-in-one application

Improve pom.xml & package.json

---

pom.xml

Bump to springboot 2.0.5 and remove already defined version in Spring-boot BOM

Bump to Springboot 2.0.5 and remove already defined dependencies

---

pom.xml
src/main/java/io/suricate/monitoring/controllers/api/ConfigurationController.java
src/main/java/io/suricate/monitoring/controllers/api/ProjectController.java
src/main/java/io/suricate/monitoring/controllers/api/RepositoryController.java
src/main/java/io/suricate/monitoring/controllers/api/SettingController.java
src/main/java/io/suricate/monitoring/controllers/api/UserController.java
src/main/java/io/suricate/monitoring/model/dto/LibraryDto.java
src/main/java/io/suricate/monitoring/model/dto/project/ProjectDto.java
src/main/java/io/suricate/monitoring/model/dto/setting/SettingDto.java
src/main/java/io/suricate/monitoring/model/dto/user/RoleDto.java
src/main/java/io/suricate/monitoring/model/dto/user/UserDto.java
src/main/java/io/suricate/monitoring/model/dto/widget/CategoryDto.java
src/main/java/io/suricate/monitoring/model/dto/widget/WidgetDto.java
src/main/java/io/suricate/monitoring/model/dto/widget/WidgetParamDto.java

Improve Swagger documentation & generate swagger.json

Improve Swagger annotations & generate swagger.json

---

README.md

Add Azure Pipeline badge

---

src/main/java/io/suricate/monitoring/configuration/ApplicationProperties.java
src/main/java/io/suricate/monitoring/configuration/security/ldap/LdapAuthentication.java
src/main/resources/application.yml

Add some options (for referral, authentication) for security with LDAP

Add more option for LDAP security

---

src/main/webapp/app/modules/dashboard/dashboard.service.ts

When a user tries to create his first dashboard, routing to "Add users" failed

Fix bug when creating first dashboard

---

pom.xml

Update info for release

---

pom.xml

Init new version

---

src/main/java/io/suricate/monitoring/BackendApplication.java
src/main/java/io/suricate/monitoring/configuration/ProxyConfiguration.java
src/main/java/io/suricate/monitoring/utils/MonitorProxySelector.java

Add proxy set up on startup

---

src/main/java/io/suricate/monitoring/model/enums/WidgetVariableType.java
src/main/java/io/suricate/monitoring/service/api/ProjectWidgetService.java
src/main/java/io/suricate/monitoring/service/nashorn/task/NashornWidgetExecuteAsyncTask.java
src/main/webapp/app/layout/header/components/add-widget-dialog/add-widget-dialog.component.html
src/main/webapp/app/modules/dashboard/components/edit-project-widget-dialog/edit-project-widget-dialog.component.html
src/main/webapp/app/modules/widget/pages/admin/configuration/configuration-list/widget-configuration-list.component.html
src/main/webapp/app/shared/pipes/password-pipe.ts
src/main/webapp/app/shared/shared.module.ts
src/main/webapp/environments/environment.local.ts

Hide secret & password

---

src/main/java/io/suricate/monitoring/controllers/api/ConfigurationController.java

Clear cache when setting configuration

---

clevercloud/war.json

Init clevercloud deployment

---

src/main/java/io/suricate/monitoring/configuration/security/ldap/UserDetailsServiceLdapAuthoritiesPopulator.java
src/main/java/io/suricate/monitoring/service/api/UserService.java
src/main/java/io/suricate/monitoring/service/mapper/UserMapper.java

#399 - Update user information when LDAP connection is set

---

src/main/webapp/app/home/components/add-dashboard-dialog/add-dashboard-dialog.component.ts
src/main/webapp/app/layout/header/components/dashboard-actions/dashboard-actions.component.ts
src/main/webapp/app/modules/dashboard/components/dashboard-screen/dashboard-screen.component.html

#410 - Fix edit dashboard issue

---

src/main/java/io/suricate/monitoring/controllers/api/CategoryController.java

#426 - Unable users to add/edit widget

---

src/main/webapp/app/modules/widget/widget.route.ts

#428 - Delete AdminGuard for widget list page

---

src/main/webapp/app/modules/dashboard/components/dashboard-screen/dashboard-screen-widget.component.scss
src/main/webapp/app/modules/dashboard/components/dashboard-screen/dashboard-screen.component.scss
src/main/webapp/sass/_dashboard-screen.scss
src/main/webapp/sass/_global-styles.scss
src/main/webapp/sass/styles.scss

430 improve the dashboard screen css

---

src/main/java/io/suricate/monitoring/model/entity/project/Project.java

#432 - Fix widget grid position

---

src/main/webapp/app/modules/dashboard/components/dashboard-screen/dashboard-screen.component.ts

#434 - Fix collision when moving widget with small height

---

src/main/java/io/suricate/monitoring/controllers/api/ProjectController.java
src/main/java/io/suricate/monitoring/service/api/ProjectService.java
src/main/webapp/app/home/components/add-dashboard-dialog/add-dashboard-dialog.component.ts
src/main/webapp/app/layout/header/components/dashboard-actions/dashboard-actions.component.html
src/main/webapp/app/layout/header/components/dashboard-actions/dashboard-actions.component.ts
src/main/webapp/app/modules/dashboard/components/dashboard-screen/dashboard-screen.component.ts
src/main/webapp/app/modules/dashboard/pages/dashboard-detail/dashboard-detail.component.ts
src/main/webapp/assets/i18n/en.json

#438 - Delete dashboard frontend management

---

src/main/java/io/suricate/monitoring/service/api/ConfigurationService.java
src/main/java/io/suricate/monitoring/service/api/ProjectWidgetService.java

#440 - Inject Global configurations in mustache template if already done

---

src/main/webapp/app/layout/sidenav/pages/sidenav.component.html

#444 - Open a new tab when click on TV icon in the sidenav

---

src/main/webapp/app/home/home.component.html
src/main/webapp/app/home/home.component.scss
src/main/webapp/app/layout/header/components/add-widget-dialog/add-widget-dialog.component.html
src/main/webapp/app/layout/header/components/add-widget-dialog/add-widget-dialog.component.scss
src/main/webapp/app/modules/dashboard/pages/dashboard-detail/dashboard-detail.component.html
src/main/webapp/app/modules/dashboard/pages/dashboard-detail/dashboard-detail.component.scss
src/main/webapp/app/modules/dashboard/pages/dashboard-detail/dashboard-detail.component.ts
src/main/webapp/app/shared/components/toast/toast.component.ts
src/main/webapp/sass/components/material/_mat-card-theme.scss

452 be able to have clickable cards on widget creation modal

---

pom.xml
src/main/webapp/app/home/home.component.html
src/main/webapp/app/home/home.component.scss
src/main/webapp/app/layout/header/components/add-widget-dialog/add-widget-dialog.component.html
src/main/webapp/app/layout/header/components/add-widget-dialog/add-widget-dialog.component.scss
src/main/webapp/app/modules/dashboard/pages/dashboard-detail/dashboard-detail.component.html
src/main/webapp/app/modules/dashboard/pages/dashboard-detail/dashboard-detail.component.scss
src/main/webapp/sass/_global-styles.scss
src/main/webapp/sass/components/material/_mat-card-theme.scss

Thank you for your contribution ! 🍹 
Closes  #464

#464 - Fix issue on card

---

src/main/webapp/app/layout/header/pages/pages-header.component.scss
src/main/webapp/app/modules/dashboard/components/dashboard-screen/dashboard-screen.component.scss
src/main/webapp/app/modules/dashboard/pages/dashboard-tv/dashboard-tv.component.scss
src/main/webapp/app/modules/dashboard/pages/dashboard-tv/dashboard-tv.component.ts
src/main/webapp/sass/components/material/_mat-sidenav-theme.scss

485 delete right scrollbar on tv url

---

pom.xml

#487 - Downgrade jasypt version

---

src/main/webapp/app/layout/header/components/add-widget-dialog/add-widget-dialog.component.ts
src/main/webapp/app/modules/dashboard/components/edit-project-widget-dialog/edit-project-widget-dialog.component.ts

#510 - Fix encryption errors

---

src/main/java/io/suricate/monitoring/service/GitService.java
src/test/java/io/suricate/monitoring/service/GitServiceTest.java

#554 - Add credentials to git clone

---

package-lock.json
package.json
pom.xml

#566 - release 2.2.0

---

package-lock.json
package.json
pom.xml

Prepare release 3.0.0

---

src/main/java/io/suricate/monitoring/service/api/WidgetService.java
src/main/java/io/suricate/monitoring/service/specification/WidgetSearchSpecification.java

Add widgets research by category name in the catalog

---

src/main/webapp/app/core/components/login/login.component.html
src/main/webapp/app/core/components/login/login.component.scss
src/main/webapp/app/core/components/register/register.component.html
src/main/webapp/app/core/components/register/register.component.scss
src/main/webapp/app/shared/components/list/list.component.ts
src/main/webapp/app/shared/components/paginator/paginator.component.html
src/main/webapp/app/shared/components/paginator/paginator.component.ts
src/main/webapp/app/shared/services/backend/http-filter.service.ts
src/main/webapp/sass/_global-styles.scss

Add pagination size options

---

src/main/webapp/app/dashboard/components/dashboard-screen/dashboard-screen-widget.component.ts
src/main/webapp/app/shared/components/form-sidenav/form-sidenav.component.html
src/main/webapp/app/shared/components/form-sidenav/form-sidenav.component.ts
src/main/webapp/app/shared/components/inputs/slide-toggle/slide-toggle.component.html
src/main/webapp/app/shared/components/inputs/slide-toggle/slide-toggle.component.scss
src/main/webapp/app/shared/components/inputs/slide-toggle/slide-toggle.component.ts
src/main/webapp/app/shared/components/wizard/wizard.component.html
src/main/webapp/app/shared/components/wizard/wizard.component.scss
src/main/webapp/app/shared/components/wizard/wizard.component.ts
src/main/webapp/app/shared/form-fields/widget-configuration-form-fields.service.ts
src/main/webapp/app/shared/form-steps/project-widget-form-steps.service.ts
src/main/webapp/app/shared/models/frontend/button/slide-toggle/slide-toggle-button-configuration.ts
src/main/webapp/app/shared/models/frontend/form/form-step.ts
src/main/webapp/app/shared/models/frontend/sidenav/form-sidenav-configuration.ts
src/main/webapp/app/shared/modules/material.module.ts
src/main/webapp/app/shared/services/frontend/form.service.ts
src/main/webapp/app/shared/shared.module.ts
src/main/webapp/assets/i18n/en.json
src/main/webapp/assets/i18n/fr.json

#574 - Override category settings during the widget addition to a dashboard

---

src/main/webapp/app/shared/components/form-sidenav/form-sidenav.component.html

#574 - Check if the toggle button configuration exists before using it

---

.gitignore
pom.xml
src/main/webapp/app/dashboard/components/dashboard-tv/dashboard-tv.component.ts
src/main/webapp/app/dashboard/services/library/library.service.ts
src/main/webapp/app/shared/services/frontend/websocket/websocket.service.ts
src/main/webapp/sass/components/material/_mat-grid-list-theme.scss

Improve widgets display. Improve Angular dark theme.

---

src/main/webapp/app/app.component.ts
src/main/webapp/app/core/components/home/home.component.ts
src/main/webapp/app/core/components/login/login.component.ts
src/main/webapp/app/core/services/settings.service.ts
src/main/webapp/app/layout/components/sidenav/sidenav.component.ts

Properly set the user's settings at the authentication

---

karma.conf.js
package.json

Add config for lauching browser in headless mode

---

src/main/webapp/app/dashboard/components/dashboard-screen/dashboard-screen-widget/dashboard-screen-widget.component.spec.ts
src/main/webapp/app/dashboard/components/dashboard-screen/dashboard-screen.component.spec.ts
src/main/webapp/app/dashboard/components/dashboard-tv/dashboard-tv.component.spec.ts
src/main/webapp/app/dashboard/components/dashboard-tv/dashboard-tv.component.ts
src/main/webapp/app/dashboard/components/tv-management-dialog/tv-management-dialog.component.html
src/main/webapp/app/dashboard/components/tv-management-dialog/tv-management-dialog.component.ts
src/main/webapp/app/mock/mock.module.ts
src/main/webapp/app/mock/services/mock-rx-stomp/mock-rx-stomp.service.spec.ts
src/main/webapp/app/mock/services/mock-rx-stomp/mock-rx-stomp.service.ts
src/main/webapp/app/mock/services/mocked-model-builder/mocked-model-builder.service.spec.ts
src/main/webapp/app/shared/directives/widget-js-scripts.directive.spec.ts
src/main/webapp/app/shared/services/frontend/websocket/websocket.service.spec.ts
src/main/webapp/app/shared/services/frontend/websocket/websocket.service.ts
src/main/webapp/app/shared/shared.module.ts

Use concepts of the last release of the stomp lib

---

src/main/webapp/app/dashboard/components/dashboard-screen/dashboard-screen.component.ts
src/main/webapp/app/dashboard/components/dashboard-tv/dashboard-tv.component.ts
src/main/webapp/app/mock/services/mock-rx-stomp/mock-rx-stomp.service.spec.ts
src/main/webapp/app/mock/services/mock-rx-stomp/mock-rx-stomp.service.ts
src/main/webapp/app/shared/services/frontend/websocket/websocket.service.ts

Ensure the connection is well opened before listening on urls

---

src/main/webapp/app/admin/repositories/repositories.component.ts
src/main/webapp/assets/i18n/en.json
src/main/webapp/assets/i18n/fr.json

Displayed info message while creating repository

---

src/main/java/io/suricate/monitoring/repositories/LibraryRepository.java
src/main/java/io/suricate/monitoring/services/api/LibraryService.java

Fixed widget display when multiple repos with multiple JS libraries

---

src/main/webapp/app/dashboard/components/dashboard-detail/dashboard-detail.component.html
src/main/webapp/app/dashboard/components/dashboard-detail/dashboard-detail.component.scss
src/main/webapp/app/dashboard/components/dashboard-detail/dashboard-detail.component.ts
src/main/webapp/sass/components/material/_mat-grid-list-theme.scss

Fixed dashboard background color display when dashboard is empty

---

src/main/webapp/app/dashboard/components/dashboard-detail/dashboard-detail.component.html

Fixed background duplication when dashboard contains widgets

---

.github/workflows/continuous_integration.yml
src/main/webapp/sass/_dashboard-screen.scss

Fixed widget blinking

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/pull_request.yml
.github/workflows/release.yml
.github/workflows/tag.yml

Added dedicated pull request action

---

src/main/webapp/app/core/components/login/login.component.html
src/main/webapp/app/core/components/login/login.component.ts

Hid "sign in with" tab when no social authentication is configured

---

src/main/java/io/suricate/monitoring/services/nashorn/script/NashornWidgetScript.java

New method that can be used in widgets to be able to check the status code of a website based on its URL

Added ability to get the status code of a website

---

src/main/java/io/suricate/monitoring/services/nashorn/script/NashornWidgetScript.java

Provided return code option on all Nashorn endpoints

---

changelog-builder.json

Added dependency updates section in release note

---

.github/workflows/tag.yml

Signed tag

---

src/main/java/io/suricate/monitoring/configuration/websocket/WebSocketEventEndpointsConfiguration.java
src/main/java/io/suricate/monitoring/controllers/handlers/GlobalDefaultExceptionHandler.java
src/main/java/io/suricate/monitoring/security/AuthenticationFailureEntryPoint.java
src/main/java/io/suricate/monitoring/security/filter/JwtTokenFilter.java
src/main/java/io/suricate/monitoring/services/api/ProjectWidgetService.java
src/main/java/io/suricate/monitoring/services/api/UserService.java
src/main/java/io/suricate/monitoring/services/api/WidgetService.java
src/main/java/io/suricate/monitoring/services/cache/CacheService.java
src/main/java/io/suricate/monitoring/services/git/GitService.java
src/main/java/io/suricate/monitoring/services/nashorn/scheduler/NashornRequestWidgetExecutionScheduler.java
src/main/java/io/suricate/monitoring/services/nashorn/services/DashboardScheduleService.java
src/main/java/io/suricate/monitoring/services/nashorn/services/NashornService.java
src/main/java/io/suricate/monitoring/services/nashorn/tasks/NashornRequestResultAsyncTask.java
src/main/java/io/suricate/monitoring/services/nashorn/tasks/NashornRequestWidgetExecutionAsyncTask.java
src/main/java/io/suricate/monitoring/services/search/SearchService.java
src/main/java/io/suricate/monitoring/services/token/JwtHelperService.java
src/main/java/io/suricate/monitoring/services/token/PersonalAccessTokenHelperService.java
src/main/java/io/suricate/monitoring/services/websocket/DashboardWebSocketService.java
src/main/java/io/suricate/monitoring/utils/FilesUtils.java
src/main/java/io/suricate/monitoring/utils/IdUtils.java
src/main/java/io/suricate/monitoring/utils/JsonUtils.java
src/main/java/io/suricate/monitoring/utils/PropertiesUtils.java
src/main/java/io/suricate/monitoring/utils/ToStringUtils.java
src/main/java/io/suricate/monitoring/utils/WidgetUtils.java
src/main/java/io/suricate/monitoring/utils/http/OkHttpClientUtils.java
src/main/java/io/suricate/monitoring/utils/http/WidgetProxySelector.java
src/main/java/io/suricate/monitoring/utils/logging/LoggingAspect.java

Used Lombok Slf4j logger

---

.github/workflows/continuous_integration.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml
.github/workflows/tag.yml

Updated deprecated actions

---

README.md
src/main/java/com/michelin/suricate/model/entities/AllowedSettingValue.java
src/main/java/com/michelin/suricate/model/entities/Asset.java
src/main/java/com/michelin/suricate/model/entities/Category.java
src/main/java/com/michelin/suricate/model/entities/CategoryParameter.java
src/main/java/com/michelin/suricate/model/entities/Library.java
src/main/java/com/michelin/suricate/model/entities/PersonalAccessToken.java
src/main/java/com/michelin/suricate/model/entities/Project.java
src/main/java/com/michelin/suricate/model/entities/ProjectGrid.java
src/main/java/com/michelin/suricate/model/entities/ProjectWidget.java
src/main/java/com/michelin/suricate/model/entities/Repository.java
src/main/java/com/michelin/suricate/model/entities/Role.java
src/main/java/com/michelin/suricate/model/entities/Setting.java
src/main/java/com/michelin/suricate/model/entities/User.java
src/main/java/com/michelin/suricate/model/entities/UserSetting.java
src/main/java/com/michelin/suricate/model/entities/Widget.java
src/main/java/com/michelin/suricate/model/entities/WidgetParam.java
src/main/java/com/michelin/suricate/model/entities/WidgetParamValue.java
src/test/java/com/michelin/suricate/services/cache/CacheServiceTest.java
src/test/java/com/michelin/suricate/services/websocket/DashboardWebSocketServiceTest.java

Passed Quality Gate

---

src/main/webapp/app/dashboard/components/wizard/add-widget-to-project-wizard/add-widget-to-project-wizard.component.ts

Fixed new widget position when a widget with large width already exist

---

src/main/webapp/app/layout/components/header/header.component.scss

Fixed padding on actions header

---

pom.xml

Removed unused release plugin

---

src/main/webapp/app/dashboard/components/dashboard-screen/dashboard-screen-widget/dashboard-screen-widget.component.html
src/main/webapp/app/dashboard/components/dashboard-screen/dashboard-screen-widget/dashboard-screen-widget.component.scss
src/main/webapp/assets/i18n/en.json
src/main/webapp/assets/i18n/fr.json

Improve widget execution warnings message rendering

---

src/main/resources/application.properties
src/main/webapp/assets/i18n/en.json
src/main/webapp/assets/i18n/fr.json

Added an error message on front-end when server returns http 500

---

pom.xml
src/main/java/com/michelin/suricate/configuration/web/WebConfig.java
src/main/resources/application.properties

Fixed actuator ldap healthcheck during startup

---

src/main/java/com/michelin/suricate/model/enums/DataTypeEnum.java
src/main/java/com/michelin/suricate/services/api/ProjectWidgetService.java
src/main/java/com/michelin/suricate/utils/PropertiesUtils.java
src/main/webapp/app/dashboard/components/dashboard-screen/dashboard-screen-widget/dashboard-screen-widget.component.ts
src/main/webapp/app/dashboard/components/wizard/add-widget-to-project-wizard/add-widget-to-project-wizard.component.ts
src/main/webapp/app/shared/components/inputs/file-input/file-input.component.ts
src/main/webapp/app/shared/components/inputs/input/input.component.html
src/main/webapp/app/shared/components/inputs/input/input.component.ts
src/main/webapp/app/shared/enums/data-type.enum.ts
src/main/webapp/app/shared/services/frontend/form-steps/project-widget-form-steps/project-widget-form-steps.service.ts
src/main/webapp/app/shared/utils/file.utils.ts
src/test/java/com/michelin/suricate/utils/PropertiesUtilsTest.java

Added text area as widget parameter

---

src/main/webapp/app/dashboard/components/dashboard-screen/dashboard-screen-widget/dashboard-screen-widget.component.ts
src/main/webapp/app/dashboard/components/wizard/add-widget-to-project-wizard/add-widget-to-project-wizard.component.ts

Fixed non-text inputs error when adding/updating a widget

---

.github/workflows/continuous_integration.yml

Fix Docker build on Java 21

---

docker-compose.yml
src/main/java/com/michelin/suricate/configuration/web/WebConfig.java
src/main/resources/application-postgresql.properties

Fix authorization request to h2 console when postgresql is enabled

---

README.md
docker-compose.yml
src/main/java/com/michelin/suricate/configuration/web/WebConfig.java
src/main/resources/application-postgresql.properties

Improve documentation regarding Java version

---

src/main/webapp/app/layout/components/menu/menu.component.scss

Fix ID provider icon display

---

src/main/webapp/app/shared/components/list/list.component.scss

Fix widget parameter overflow on config admin menu

---

README.md
src/main/java/com/michelin/suricate/model/dto/api/error/ApiErrorDto.java
src/main/java/com/michelin/suricate/services/js/script/JsEndpoints.java
src/main/java/com/michelin/suricate/utils/exceptions/ApiException.java
src/main/java/com/michelin/suricate/utils/http/OkHttpClientUtils.java
src/main/webapp/app/admin/configurations/configurations.component.ts
src/main/webapp/app/admin/dashboards/dashboards.component.ts
src/main/webapp/app/admin/repositories/repositories.component.ts
src/main/webapp/app/admin/users/users.component.ts
src/main/webapp/app/dashboard/components/wizard/add-widget-to-project-wizard/add-widget-to-project-wizard.component.ts
src/main/webapp/app/shared/components/inputs/checkbox/checkbox.component.ts
src/main/webapp/app/shared/components/inputs/color-picker/color-picker.component.ts
src/main/webapp/app/shared/components/inputs/fields/fields.component.ts
src/main/webapp/app/shared/components/inputs/file-input/file-input.component.ts
src/main/webapp/app/shared/components/inputs/input/input.component.ts
src/main/webapp/app/shared/components/inputs/mosaic/mosaic.component.ts
src/main/webapp/app/shared/components/list/list.component.ts
src/main/webapp/app/shared/components/wizard/wizard.component.ts
src/main/webapp/app/widget/catalog/catalog.component.ts

Replace injector instance by inject

---

package.json

Update Jquery 3.7.1

---

package.json

Fix prettier versions

---

src/main/webapp/app/shared/directives/hide-after-init/hide-after-init.directive.ts

Fix widget rendering in TV view

---

LICENSE

Update LICENSE owner

---

README.md
pom.xml

Upgrade to GraalVM Polyglot 23.1.2

---

.github/workflows/pull_request.yml

Run Docker build on PRs

---

src/test/java/com/michelin/suricate/service/api/CategoryParametersServiceTest.java
src/test/java/com/michelin/suricate/service/api/ProjectWidgetServiceTest.java
src/test/java/com/michelin/suricate/service/api/UserServiceTest.java
src/test/java/com/michelin/suricate/service/mapper/CategoryMapperTest.java
src/test/java/com/michelin/suricate/service/mapper/ProjectGridMapperTest.java
src/test/java/com/michelin/suricate/service/mapper/ProjectMapperTest.java
src/test/java/com/michelin/suricate/service/mapper/UserMapperTest.java
src/test/java/com/michelin/suricate/service/mapper/UserSettingMapperTest.java
src/test/java/com/michelin/suricate/service/mapper/WidgetMapperTest.java
src/test/java/com/michelin/suricate/service/mapper/WidgetParamValueMapperTest.java
src/test/java/com/michelin/suricate/util/WidgetUtilsTest.java

Fix typos in unit tests

---

pom.xml
src/main/java/com/michelin/suricate/configuration/web/WebConfig.java
src/main/java/com/michelin/suricate/controller/ConfigurationController.java

Upgrade and fix checkstyle v10.18.1

---

README.md

Clarify documentation about registration and database authentication
